# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [1]:
#Ejercicio 1
#Crear un arreglo de ceros de longitud 12

#importamos libreria numpy
import numpy as np
#creamos el arreglo y mostramos en pantalla
arreglo1 = np.zeros(12)
print(f'El arreglo de ceros de longitud 12 es {arreglo1}')

El arreglo de ceros de longitud 12 es [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
#Ejercicio 2
#Crear un arreglo de longitud 10 con ceros en todas
#sus posiciones y un 10 en la posición número 5

#creamos arreglo de longitud 10 con ceros en todas las posciones
arreglo2 = np.zeros(10)
#cambiamos el valor de la posición 10 por el numero 5
arreglo2[4] = 10
print('El arreglo de longitud 10 con un 10 en la posición número 5 queda', arreglo2)


El arreglo de longitud 10 con un 10 en la posición número 5 queda [ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


In [5]:
#Ejercicio 3
#Crear un arreglo que tenga los números del 10 al 49

#creamos arreglo
arreglo3 = np.arange(10,50) #recordar que el último elemento no lo considera
#vemos en pantalla
print(f'El arreglo con números del 10 al 49 es: {arreglo3}')

El arreglo con números del 10 al 49 es: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [6]:
#Ejercicio 4
#Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8

#creamos un arreglo con los numeros de 0 al 8
arreglo4 = np.arange(9)
#usamos el comando resize para darle la forma de (3,3)
nuevo_arreglo4 = np.resize(arreglo4,(3,3))
#mostramos en pantalla
print('El arreglo 2D con números del 0 al 8 queda:')
print(nuevo_arreglo4)

El arreglo 2D con números del 0 al 8 queda:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
#Ejercicio 5
#Crear un arreglo de números aleatorios de longitud 100 
#y obtener su media y varianza

#creamos un arreglo de números aleatorios de longitud 100
arreglo5 = np.random.rand(100)
#calculamos la media y mostramos en pantalla
media =  np.mean(arreglo5)
print(f'La media del arreglo de números aleatorios es: {media:.2f}')
#calculamos la varianza y mostramos en pantalla
varianza = np.var(arreglo5)
print(f'La varianza del arreglo de números aleatorios es: {varianza:.2f}')


La media del arreglo de números aleatorios es: 0.49
La varianza del arreglo de números aleatorios es: 0.08


In [12]:
#Ejercicio 6
#Calcular la media de un arreglo usando np.sum
#defino arreglo
arreglo6 = nuevo_arreglo4
print('Arreglo:')
print(arreglo6)
#calculo la media usando np.sum y la longitud usando size
lon = arreglo6.size #devuelve la longitud
media = np.sum(arreglo6) / lon
#muestro en pantalla el resultado
print(f'La media del arreglo es: {media:.2f}')

#Ejercicio 7
#Calcular la varianza de un arreglo usando np.sum y np.mean
#definimos la varianza
varianza = np.sum((arreglo6 - media)**2) / lon
#muestro resultado en pantalla
print(f'La varianza del arreglo es {varianza:.2f}')

Arreglo:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
La media del arreglo es: 4.00
La varianza del arreglo es 6.67


In [15]:
#Ejercicio 8
#Crear un array de números aleatorios usando np.random.randn y muestro 2 decimales usando .round
arreglo8 = np.round(np.random.randn(20),2)
print('El arreglo de números aleatorios es:')
print(arreglo8)

El arreglo de números aleatorios es:
[-1.14  0.99  0.9   1.66 -0.67 -2.02 -1.49 -0.57  1.26  1.08  0.76 -1.04
 -0.87 -0.87  1.35  1.82  0.04  0.44  0.94 -0.04]
